backend:
  name: github
  repo: lutfiandri/batur-bertutur
  branch: main
media_folder: /public/uploads
public_folder: /uploads
collections:
  - name: home
    label: Home
    create: false
    delete: false
    folder: _posts/home
    slug: '{{slug}}'
    fields:
      - name: title
        label: Judul
        widget: string
      - name: body
        label: Deskripsi
        widget: markdown
      - name: gallery
        label: Galeri
        widget: list
        fields:
          - label: Gambar
            name: image
            widget: image

  - name: wisata
    label: Wisata
    create: true
    folder: _posts/wisata
    slug: '{{slug}}'
    fields:
      - label: Judul
        name: title
        widget: string
      - label: Deskripsi
        name: desc
        widget: string
      - label: Tampilkan di halaman utama
        name: featured
        widget: boolean
      - label: Gambar Thumbnail
        name: thumbnail
        widget: image
      - label: Tanggal Publish
        name: date
        widget: datetime
      - label: Tag (pisahkan dengan koma)
        name: tags
        widget: string
        hint: 'Contoh: KKN-PPM UGM, Wisata'
      - label: Lokasi (latitude, longitude)
        name: location
        widget: string
        hint: 'Bisa didapatkan dari google maps'
      - label: Isi Halaman
        name: body
        widget: markdown
      - label: Link Google Maps
        name: googleMapsUrl
        widget: string
      - label: Link Instagram
        name: instagramUrl
        widget: string
        required: false
      - label: Fasilitas (pisahkan dengan koma)
        name: facilities
        widget: string
        required: false
        hint: 'Contoh: Toilet, Warung Jajan, Musholla'
      - label: Galeri
        name: gallery
        widget: list
        fields:
          - label: Gambar
            name: image
            widget: image
      - label: Files
        name: files
        widget: list
        fields:
          - label: File
            name: file
            widget: file

  - name: blog
    label: Blog
    create: true
    folder: _posts/blog
    slug: '{{slug}}'
    fields:
      - label: Judul
        name: title
        widget: string
      - label: Deskripsi
        name: desc
        widget: string
      - label: Tampilkan di halaman utama
        name: featured
        widget: boolean
      - label: Gambar Thumbnail
        name: thumbnail
        widget: image
      - label: Tanggal Publish
        name: date
        widget: datetime
      - label: Tag (pisahkan dengan koma)
        name: tags
        widget: string
        hint: 'Contoh: KKN-PPM UGM, Wisata'
      - label: Isi Halaman
        name: body
        widget: markdown
      - label: Files
        name: files
        widget: list
        fields:
          - label: File
            name: file
            widget: file
